"""initial

Revision ID: bef00c94f341
Revises: 3bd025e23b5e
Create Date: 2026-06-25 15:36:29.955033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bef00c94f341'
down_revision: Union[str, None] = '3bd025e23b5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasil_ujian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ujian_siswa_id', sa.Integer(), nullable=False),
    sa.Column('skor', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hasil_ujian_id'), 'hasil_ujian', ['id'], unique=False)
    op.create_table('jadwal_ujian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paket_ujian_id', sa.Integer(), nullable=False),
    sa.Column('mulai', sa.DateTime(), nullable=False),
    sa.Column('selesai', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jadwal_ujian_id'), 'jadwal_ujian', ['id'], unique=False)
    op.create_table('jawaban_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ujian_siswa_id', sa.Integer(), nullable=False),
    sa.Column('soal_id', sa.Integer(), nullable=False),
    sa.Column('jawaban', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jawaban_siswa_id'), 'jawaban_siswa', ['id'], unique=False)
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kelas_id'), 'kelas', ['id'], unique=False)
    op.create_table('log_kecurangan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ujian_siswa_id', sa.Integer(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_kecurangan_id'), 'log_kecurangan', ['id'], unique=False)
    op.create_table('opsi_jawaban',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soal_id', sa.Integer(), nullable=False),
    sa.Column('teks_opsi', sa.String(length=1000), nullable=False),
    sa.Column('is_benar', sa.Boolean(), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opsi_jawaban_id'), 'opsi_jawaban', ['id'], unique=False)
    op.create_table('paket_ujian',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('durasi_menit', sa.Integer(), nullable=False),
    sa.Column('jumlah_soal', sa.Integer(), nullable=False),
    sa.Column('is_random_soal', sa.Boolean(), nullable=True),
    sa.Column('is_random_opsi', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paket_ujian_id'), 'paket_ujian', ['id'], unique=False)
    op.create_table('pelajaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pelajaran_id'), 'pelajaran', ['id'], unique=False)
    op.create_table('pengaturan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_pengaturan_id'), 'pengaturan', ['id'], unique=False)
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_id'), 'program', ['id'], unique=False)
    op.create_table('soal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paket_ujian_id', sa.Integer(), nullable=True),
    sa.Column('pelajaran_id', sa.Integer(), nullable=True),
    sa.Column('teks_soal', sa.Text(), nullable=False),
    sa.Column('tipe', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soal_id'), 'soal', ['id'], unique=False)
    op.create_table('ujian_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('siswa_id', sa.Integer(), nullable=False),
    sa.Column('paket_ujian_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ujian_siswa_id'), 'ujian_siswa', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=200), nullable=False),
    sa.Column('no_induk', sa.String(length=50), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_induk')
    )
    op.create_index(op.f('ix_siswa_id'), 'siswa', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_siswa_id'), table_name='siswa')
    op.drop_table('siswa')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_ujian_siswa_id'), table_name='ujian_siswa')
    op.drop_table('ujian_siswa')
    op.drop_index(op.f('ix_soal_id'), table_name='soal')
    op.drop_table('soal')
    op.drop_index(op.f('ix_program_id'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_pengaturan_id'), table_name='pengaturan')
    op.drop_table('pengaturan')
    op.drop_index(op.f('ix_pelajaran_id'), table_name='pelajaran')
    op.drop_table('pelajaran')
    op.drop_index(op.f('ix_paket_ujian_id'), table_name='paket_ujian')
    op.drop_table('paket_ujian')
    op.drop_index(op.f('ix_opsi_jawaban_id'), table_name='opsi_jawaban')
    op.drop_table('opsi_jawaban')
    op.drop_index(op.f('ix_log_kecurangan_id'), table_name='log_kecurangan')
    op.drop_table('log_kecurangan')
    op.drop_index(op.f('ix_kelas_id'), table_name='kelas')
    op.drop_table('kelas')
    op.drop_index(op.f('ix_jawaban_siswa_id'), table_name='jawaban_siswa')
    op.drop_table('jawaban_siswa')
    op.drop_index(op.f('ix_jadwal_ujian_id'), table_name='jadwal_ujian')
    op.drop_table('jadwal_ujian')
    op.drop_index(op.f('ix_hasil_ujian_id'), table_name='hasil_ujian')
    op.drop_table('hasil_ujian')
    # ### end Alembic commands ###
