"""phase4 jadwal_ujian and siswa schema

Revision ID: d65eec74f633
Revises: ef1f2d3c4b5a
Create Date: 2026-07-03 15:41:45.903507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd65eec74f633'
down_revision: Union[str, None] = 'ef1f2d3c4b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jadwal_ujian', sa.Column('program_id', sa.Integer(), nullable=True))
    op.add_column('jadwal_ujian', sa.Column('kelas_id', sa.Integer(), nullable=True))
    op.add_column('jadwal_ujian', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_login_activity_id'), 'login_activity', ['id'], unique=False)
    op.add_column('siswa', sa.Column('kelas_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('siswa', 'kelas_id')
    op.drop_index(op.f('ix_login_activity_id'), table_name='login_activity')
    op.drop_column('jadwal_ujian', 'is_deleted')
    op.drop_column('jadwal_ujian', 'kelas_id')
    op.drop_column('jadwal_ujian', 'program_id')
    # ### end Alembic commands ###
